#!/usr/bin/env bash
# this bash script displays DNS records containing record type, IP, subdomains

print_dom_subdom () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_dom_subdom "$2.$1" "$2"
else
    print_dom_subdom "www.$1" "www"
    print_dom_subdom "lb-01.$1" "lb-01"
    print_dom_subdom "web-01.$1" "web-01"
    print_dom_subdom "web-02.$1" "web-02"
fi
