#!/usr/bin/env bash
# this bash script displays DNS records containing record type, IP, subdomains

function domain_checker {
	domain_names=("www" "lb-01" "web-01" "web-02")

	for i in "${domain_names[@]}";
	do
		dig "${i}"."$1" | grep -A1 'ANSWER SECTION:' | \
		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
	done
}

function subdomain_checker {
	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ $# -lt 1 ]
then
	echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
	domain_checker "$1";
else
	subdomain_checker "$1" "$2";
fi
