#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

HRS=0
while [ $HRS -lt 13 ]
do
    echo "Hour: $HOURS"
    MINS=1
    while [ $MINS -lt 60 ]
    do
        echo $MINS
	let MINS+=1
    done
    let HRS+=1
done 
