#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements;
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.update
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.update
echo "8.8.8.8 facebook.com" >> ~/hosts.update
cp -f ~/hosts.update /etc/hosts
