#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.
# ifconfig display the info, grep allows only info with 'inet addr:' to show
# cut, further refines to show second field after the ':', thereby removing
# 'inet addr:', it also further removes any spaces at the end

ifconfig | grep 'inet addr:' | cut -d: -f2 | cut -d" " -f1
